set -g window-status-format " #I:#(~/.tmux-window-name.sh '#{pane_current_command}' '#{b:pane_current_path}' '#{pane_pid}') "
set -g window-status-style "bg=default,fg=default,none"
set -g window-status-current-format " #I:#(~/.tmux-window-name.sh '#{pane_current_command}' '#{b:pane_current_path}' '#{pane_pid}') "
set -g window-status-current-style "bg=default,fg=default,reverse,bold"
set -gF window-status-separator ""
